YupanquiAdministracion/Cuotas/urls.py
from django.urls import path
from .views import   BuscarSocio, PagoCuotaCreateView, CuotasSocialesListView, PagoCuotaActCreateView, ReporteCuotasAct

urlpatterns = [

    path('', BuscarSocio.as_view(), name='index_cuotas'),  
        # cuota Social 
    path('pago_cuota/<int:socio_id>', PagoCuotaCreateView.as_view(), name='pago_cuota'),
    path('cuotas_anuales/<int:socio_id>/', CuotasSocialesListView.as_view(), name='cuotas_anuales'),
    #     cuota actividades
    path('pago_actividad/<int:socio_id>/', PagoCuotaActCreateView.as_view(), name='pago_cuota_act'),
    path('cuotas_actividad/<int:socio_id>/',ReporteCuotasAct.as_view(), name='cuotas_actividad'),

    

   
]

YupanquiAdministracion/Socios/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls.static import static






urlpatterns =[
   
    path('/',views.BuscarSocioView.as_view(),name='index_socios'),
    path('detalle_socio/<int:pk>', views.DetalleSocio.as_view(), name="detalle_socio"),
    path('crear_socio',views.CrearSocio.as_view(), name='crear_socio'),
    path('editar_socio/<int:pk>',views.EditarSocio.as_view(), name="editar_socio"),
    path('eliminar_socio/<int:pk>', views.EliminarSocio.as_view(), name="eliminar_socio"),  
    path('buscar',views.BuscarSocioView.as_view(), name="buscar_socio") , 

    
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

YupanquiAdministracion/YupanquiAdministracion/urls.py
"""
URL configuration for YupanquiAdministracion project.

The `urlpatterns` list routes URLs to views. For more information please see:
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
# from Usuarios.views import LoginFormView
from django.contrib.auth.decorators import login_required
from Administracion.views import ErrorView


urlpatterns = [
 
    path('admin/', admin.site.urls),    
    path('lagout/',auth_views.LogoutView.as_view(template_name='accounts/login/'), name='lagout'),
    
    path('/', include("Socios.urls")),    
    path('administracion/',include("Administracion.urls")), 
    path('cuotas/', include("Cuotas.urls")),
    path('inscripcion/', include("Inscripcion.urls")) , 
    path('accounts/', include("django.contrib.auth.urls")),
    
    path('error/',login_required(ErrorView.as_view()),name='error_permiso')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

YupanquiAdministracion/Socios/models.py
from django.db import models

# Create your models here.
class Socio(models.Model):

    GENEROS = [
        (1,'Masculino'),
        (2,'Femenino'),
        (3,'Otro'),
            ]
    ESTADOS =[
        (1,'Activo'),
        (2,'Inactivo')
    ]
    nroSocio = models.IntegerField(verbose_name='Nro de Socio', unique=True ,null=False)
    nombre = models.CharField(max_length=100,verbose_name='Nombre')
    apellido = models.CharField(max_length=150,verbose_name='Apellido')
    genero = models.IntegerField(choices = GENEROS, default=1)
    email = models.EmailField(max_length=150,null=True)
    dni = models.IntegerField(verbose_name="DNI")
    tel = models.IntegerField(verbose_name='Tel')
    calle = models.CharField(max_length=100,verbose_name='Calle')
    nro = models.IntegerField(verbose_name='Nro')
    localidad= models.CharField(max_length=50, verbose_name='Localidad')
   
    foto = models.ImageField(upload_to='imagenes',null=True,verbose_name='Foto',blank=True)
    estado = models.IntegerField(choices=ESTADOS,default=1)
    observaciones_importantes=models.TextField(max_length=100, null=True, blank=True, verbose_name='Observaciones Importantes')
    
    def __str__(self):
        return f"{self.nroSocio}  -  {self.nombre}    {self.apellido}" 

YupanquiAdministracion/Socios/forms.py
from django import forms
from .models import Socio

class SocioForm(forms.ModelForm):

     class Meta:
          model = Socio
          fields = '__all__'

YupanquiAdministracion/Socios/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Socio
from .forms import SocioForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import  UserPassesTestMixin
from django.contrib import messages
# Create your views here.

class BuscarSocioView(LoginRequiredMixin,ListView):
    model = Socio
    template_name = 'socios/index_socios.html'
    context_object_name = 'socios'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Socio.objects.filter(nroSocio__icontains=query) | Socio.objects.filter(apellido__icontains=query) | Socio.objects.filter(dni__icontains=query)
        return Socio.objects.all()
    
class DetalleSocio(LoginRequiredMixin,DetailView):
   
    model = Socio
    context_object_name = 'detalle_socio'
    context_object_name = 'socio'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agregar las inscripciones asociadas al contexto
        context['inscripciones'] = self.object.inscripciones.all()
        return context
  

class CrearSocio(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Socio   
    form_class = SocioForm
    template_name = 'socios/crear_socio.html'
    success_url = reverse_lazy('index_socios')

    def test_func(self):       
        return self.request.user.groups.filter(name='Administrativo').exists()
    
    def handle_no_permission(self):
        return redirect('error_permiso')
    
    def form_valid(self, form):
        # Puedes agregar lógica adicional antes de guardar el formulario, si es necesario
        messages.success(self.request, 'Socio registrado exitosamente.')
        return super().form_valid(form)

    def form_invalid(self, form):
        # Puedes agregar lógica adicional para manejar el caso cuando el formulario no es válido
        messages.error(self.request, 'Error al registrar Socio. Por favor, revise los campos.')
        return super().form_invalid(form)

class EditarSocio(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Socio
    form_class= SocioForm
    template_name = 'socios/editar_socio.html'  
    success_url = reverse_lazy("index_socios")

    def test_func(self):       
        return self.request.user.groups.filter(name='Administrativo').exists()
    
    def handle_no_permission(self):
        return redirect('error_permiso')
    
    def form_valid(self, form):
        # Puedes agregar lógica adicional antes de guardar el formulario, si es necesario
        messages.success(self.request, 'Socio modificado exitosamente.')
        return super().form_valid(form)

    def form_invalid(self, form):
        # Puedes agregar lógica adicional para manejar el caso cuando el formulario no es válido
        messages.error(self.request, 'Error al modificar el Socio. Por favor, revise los campos.')
        return super().form_invalid(form)



class EliminarSocio(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Socio
    template_name = 'socios/eliminar_socio.html'
    success_url = reverse_lazy("index_socios")

    def test_func(self):       
        return self.request.user.groups.filter(name='Administrativo').exists()
    
    def handle_no_permission(self):
        return redirect('error_permiso')

YupanquiAdministracion/templates/socios/crear_socio.html
{%extends 'layouts/base.html'%} 
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}CREAR SOCIO{% endblock titulo %}

{% block content %}

<div class="container">
    <div class="row">
<div class="col"></div>
<div class="col">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        {{ form|crispy}}
        
        <div class="text-center">
            <input class="btn btn-lg btn-secondary" type="submit" value="CREAR SOCIO">
            <a href="{%url 'index_socios' %}" class="btn btn-primary" >Volver</a>
        </div>
            </form>
</div>
<div class="col"></div>
      


    </div>
</div>




{% endblock content %}

YupanquiAdministracion/templates/socios/editar_socio.html
{% extends "layouts/base.html" %}
{% load static %}
{% block titulo %}EDITAR ACTIVIDAD{% endblock titulo %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col"></div>       
        
        <div class="col">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                
                {{ form|crispy}}
                
                <div class="text-center">
                    <input class="btn btn-md btn-success " type="submit" value="MODIFICAR SOCIO"><a href="{%url 'index_socios' %}" class="btn btn-primary" >Volver</a>
                </div>
                    </form>
        </div>
        <div class="col"></div>
    </div>
</div>
  

</div>


{% endblock content %}

YupanquiAdministracion/templates/socios/eliminar_socio.html
 {% extends "layouts/base.html" %}
{% load static %}
{% block titulo %}Eliminar {% endblock titulo %}


{% block content %}
<div class="center-block">
    <div class="row">
   
   <div>
       <form action="" method="post">
   {% csrf_token %}
   <p><h3>¿Desear eliminar <strong> {{object.nombre}} {{object.apellido}},Nº Socio: {{object.nroSocio}}?</strong></h3></p>
   

   <div class="text-center">
       <input class="btn btn-lg btn-danger" type="submit" value="Eliminar Socio">
   </div><a href="{%url 'index_socios' %}" class="btn btn-primary" >Volver</a>
       </form>
   
   </div>
   
   </div> 
   </div> 

    
       
   
{% endblock content %} 

YupanquiAdministracion/templates/socios/index_socios.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
   
{% for message in messages %}
    <div class="{% if message.tags %}alert alert-{{ message.tags }}{% endif %}">
        {{ message }}
    </div>
{% endfor %}
    <a href="{%url 'crear_socio' %}" class="btn btn-success btn-lm">NUEVO SOCIO</a>

    <form method="get" action="{% url 'index_socios' %}" class="mb-3">
        <div class="input-group">
            <input type="text" id="q" name="q" class="form-control" placeholder="Nro Socio, Dni, Apellido">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nro. Socio</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Acciones</th>
               
                
            </tr>
        </thead>
        <tbody>
            {% for socio in socios %}
                <tr>
                    <td>{{ socio.nroSocio }}</td>
                    <td>{{ socio.nombre }}</td>
                    <td>{{ socio.apellido }}</td>
                    
                    
                      <td>
                       <a  class="btn btn-warning btn-sm " href="{% url 'editar_socio' socio.id %}">Editar</a>
                       <a class="btn btn-danger btn-sm" href="{% url 'eliminar_socio' socio.id %}">Eliminar</a>
                       <a class="btn btn-primary btn-sm" href="{% url 'detalle_socio' socio.id %}">Detalle</a>
                      </td>
                     
                    <th>
                       
                        
              {% endfor %}         
                
           
        </tbody>
    </table>
</div>

{% endblock content %}

YupanquiAdministracion/templates/socios/socio_detail.html
{%extends 'layouts/base.html'%} 
{% comment %} {% load static %} {% endcomment %}
{% block titulo %}DETALLE SOCIO{% endblock titulo %}

{% block content %}

<a href="{%url 'index_socios' %}" class="btn btn-primary" >Volver</a> <a class="btn btn-success btn-md"href="{% url 'inscripcion' socio.id %}">INSCRIBIR A UNA ACTIVIDAD</a>
<style>
  /* Estilo para el contenedor de la foto carnet */
  .foto-carnet {
      border: 2px solid #000;
      padding: 10px;
      width: 150px; /* Ajusta el tamaño según sea necesario */
      height: 200px; /* Ajusta el tamaño según sea necesario */
      text-align: center;
  }

  /* Estilo para la foto dentro del contenedor */
  .foto-carnet img {
      max-width: 100%;
      max-height: 100%;
  }
</style><div class="container">

    <div class="card">
      <!-- Foto de socio en la esquina superior izquierda -->
      {% comment %} <img class="card-img-top" src="{{ socio.foto.url }}" alt="Foto de socio"> {% endcomment %}
      {% comment %} <div class="card-body">
        <!-- Datos del socio -->
      <div class="foto-carnet">  <h5 class="card-title">{{ object.nombre }} {{ object.apellido }}</h5>
        {% if socio.foto %}
        <img src="{{ object.foto.url }}" alt="Foto de {{ object.nombre }} {{ object.apellido }}">
    {% else %}
        <p>No hay foto disponible</p>
    {% endif %}
  </div>
        <p class="card-text">Número de Socio: {{ object.nroSocio }}</p>
        <p class="card-text">Género: {{object.get_genero_display }}</p>
        <p class="card-text">Email: {{ object.email }}</p>
        <p class="card-text">DNI: {{ object.dni }}</p>
        <p class="card-text">Teléfono: {{ object.tel }}</p>
        <p class="card-text">Dirección: {{ object.calle }} {{ object.nro }}, {{ object.localidad }}</p>
        <p class="card-text">Estado: {{ object.get_estado_display }}</p>
        <p class="card-text bx-1">Estado: {{ object.observaciones_importantes }}</p>
        p
      </div>
    </div>
  </div>" {% endcomment %}
  <style>
    /* Estilo para el contenedor de la foto carnet */
    .foto-carnet {
        border: 2px solid #000;
        padding: 10px;
        width: 150px; /* Ajusta el tamaño según sea necesario */
        height: 200px; /* Ajusta el tamaño según sea necesario */
        text-align: center;
    }

    /* Estilo para la foto dentro del contenedor */
    .foto-carnet img {
        max-width: 100%;
        max-height: 100%;
    }
</style>

<div class="container">
    <div class="row">
        <!-- Columna para la foto -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <div class="foto-carnet">
                        
                        {% if socio.foto %}
                            <img src="{{ object.foto.url }}" alt="Foto de {{ object.nombre }} {{ object.apellido }}">
                        {% else %}
                            <p>No hay foto disponible</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <!-- Columna para los datos del socio -->
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <p class="card-text"><strong><h5 class="card-title">{{ object.nombre }} {{ object.apellido }}</h5></strong></p>
                    <p class="card-text">Número de Socio: <strong> {{ object.nroSocio }}</strong></p>
                    <p class="card-text">Género: <strong>{{object.get_genero_display }}</strong></p>
                    <p class="card-text">Email: <strong>{{ object.email }}</strong></p>
                    <p class="card-text">DNI: <strong>{{ object.dni }}</strong></p>
                    <p class="card-text">Teléfono: <strong>{{ object.tel }}</strong></p>
                    <p class="card-text">Dirección:<strong> {{ object.calle }} {{ object.nro }}, {{ object.localidad }}</strong></p>
                    <p class="card-text">Estado: {{ object.get_estado_display }}</strong></p>
                    <p class="card-text bx-1">Observaciones: {{ object.observaciones_importantes }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

  
  <div class="container">

    {% for inscripcion in inscripciones %}
    <div class="card">
      <div class="card-body">
        <a href="{% url 'editar_inscripcion' inscripcion.pk %}" class="btn btn-warning btn-sm"> editar</a>
        <a href="{%url 'eliminar_inscripcion' inscripcion.pk %}" class="btn btn-danger btn-sm" >Eliminar</a>
        <!-- Datos de la inscripción -->
        <h5 class="card-title">Inscripto en : {{ inscripcion.actividad }}</h5>
        <p class="card-text">Fecha de Inscripción: {{ inscripcion.fecha_inscripcion }}</p>
        <p class="card-text">Actividad: {{ inscripcion.actividad }}</p>
        <p class="card-text">Categoría: {{ inscripcion.categoria }}</p>
      </div>
    </div>
  </div>
  {% endfor %}
  

  
   
</div>

{% endblock content %}

YupanquiAdministracion/templates/socios/socios.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    

    <form method="get" action="{% url 'lista_socios' %}" class="mb-3">
        <div class="input-group">
            <input type="text" id="q" name="q" class="form-control" placeholder="Nombre o Apellido">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </form>
   
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nro. Socio</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Pagar</th>
                <th>Detalle</th>
                
            </tr>
        </thead>
        <tbody>
            {% for socio in socios %}
                <tr>
                    <td>{{ socio.nroSocio }}</td>
                    <td>{{ socio.nombre }}</td>
                    <td>{{ socio.apellido }}</td>
                  
                      <td>  
                        <a href="{% url 'detalle_socio' socio.id %}" class="btn btn-secondary" >Cuota Social</a>
                    
                      <a  href="{% url 'editar_socio' socio.id %}"class="btn btn-warning">Cuota Actividad</a>
                      
                      </td>
                      <td>
                        <a href="{% url 'eliminar_socio' socio.id %}" class="btn btn-primary">Ver mas</a>
                      </td>
                    <th>
                       
                        
              {% endfor %}         
                
           
        </tbody>
    </table>
</div>

  
{% endblock content%}